### ISSUE TITLE
Infografía 

### ISSUE THREAD

**Issue by Paola939** [SistemasTecTlaxiaco/infografia-Paola939#3]
[Paola_Rosario_ infografía .pdf](https://github.com/SistemasTecTlaxiaco/infografia-Paola939/files/12555101/Paola_Rosario_.infografia.pdf)

**Comment by Felix-Angel** [comment]
Redacción y ortografía: 10%
Exposición de ideas centrales 13% (No cuenta con 10 ideas principales)
Organización de  la información: 15%
Uso de imágenes y colores: 15%
Presentación visual: 15%
Referencias: 15%
Presentación: 15%
Calificación: 19.6/20
Calificado por equipo "Mayra, Daniel, Diego, Félix"

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
